apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-ml
  labels:
    app: restful-ml
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restful-ml
  template:
    metadata:
      labels:
        app: restful-ml
    spec:
      containers:
        - name: restful-ml
          image: "restful-ml:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env
          env:
            # TODO: build the version here from .Values, currently VERSION is
            # passed down during deployment for symmetry with prefect deployment
            - name: VERSION
              value: {{ required "pass the version by hand" .Values.version | quote }}
          {{- end }}
      restartPolicy: Always
