repositories:
  - name: community-charts
    url: https://community-charts.github.io/helm-charts

  - name: twuni
    url: https://helm.twun.io

  - name: prefect
    url: https://prefecthq.github.io/prefect-helm

releases:
  - name: supa # the repo-provided index.yaml is wrong so we pullin
    chart: ./supabase-kubernetes/charts/supabase
    values:
      - supabase-values.yaml

  - name: mlflow
    chart: community-charts/mlflow

  - name: prefect-worker
    chart: prefect/prefect-worker
    values:
      - prefect-worker-values.yaml

  - name: prefect-server
    chart: prefect/prefect-server
    values:
      - prefect-service-values.yaml

  - name: generic
    chart: ./generic

  - name: vectorstore
    chart: ./vectorstore
