apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: {{ .Values.name }}
