apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: comandline
  name: comandline
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: comandline
  template:
    metadata:
      labels:
        io.kompose.network/stateful-ml-network: "true"
        io.kompose.service: comandline
    spec:
      containers:
        -
          command:
            - bash
          args:
            - "-c"
            - "trap : TERM INT; sleep infinity & wait"
          image: ubuntu
          name: comandline
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TESTENVVAR
              value: hi
      restartPolicy: Always
