apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: terminal
  name: terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: terminal
  template:
    metadata:
      labels:
        io.kompose.network/stateful-ml-network: "true"
        io.kompose.service: terminal
    spec:
      containers:
        - image: stateful-ml-terminal
          name: terminal
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Never
          securityContext:
            privileged: true
