apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-ml
  labels:
    app: restful-ml
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restful-ml
  template:
    metadata:
      labels:
        app: restful-ml
    spec:
      containers:
        - name: restful-ml
          image: "restful-ml:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env
          env:
          {{- range .Values.models }}
            - name: {{ .project | upper | replace "-" "_" }}_IDENTIFIER
              value: "{{ .identifier }}"
          {{- end }}
      restartPolicy: Always
