apiVersion: v1
kind: Service
metadata:
  name: restful-ml
  labels:
    app: restful-ml
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: restful-ml
