apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-admin-binding
subjects:
  - kind: ServiceAccount
    name: ci
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

# ---

# # super sketchy but i want to simplify the steps to run this example
# # this is shit though because ngrok wants me to use k8s gwapi
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: kubernetes-api-ingress
# spec:
#   ingressClassName: ngrok
#   rules:
#     - host: {{ .Values.api.ingress.host }}
#       http:
#         paths:
#           - path: {{ .Values.api.ingress.path }}
#             pathType: Prefix
#             backend:
#               service:
#                 name: kubernetes
#                 port:
#                   number: 443
