apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-deployment
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      labels:
        app: terminal
    spec:
      containers:
      - name: terminal-container
        image: stateful-ml-terminal:latest
        imagePullPolicy: Never
        tty: true
        stdin: true
        envFrom:
        - configMapRef:
            name: env
