repositories:
  - name: ngrok
    url: https://charts.ngrok.com

releases:
  - name: ngrok-ingress-controller
    chart: ngrok/kubernetes-ingress-controller
    values:
      - useExperimentalGatewayApi: false
      - credentials:
          apiKey: {{ requiredEnv "NGROK_API_KEY" }}
          authtoken: {{ requiredEnv "NGROK_AUTHTOKEN" }}
