repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: twuni
    url: https://helm.twun.io

  - name: prefect
    url: https://prefecthq.github.io/prefect-helm

releases:
  - name: supa # the repo-provided index.yaml is wrong so we pullin
    chart: ./supabase-kubernetes/charts/supabase
    values:
      - supabase-values.yaml

  - name: mlflow
    chart: bitnami/mlflow
    version: 2.3.1
    values:
      - mlflow-values.yaml

  - name: prefect-worker
    chart: prefect/prefect-worker
    version: 2024.12.25072305
    values:
      - prefect-worker-values.yaml

  - name: prefect-server
    chart: prefect/prefect-server
    version: 2024.12.25072305
    values:
      - prefect-server-values.yaml

  - name: generic
    chart: ./generic

  - name: vectorstore
    chart: ./vectorstore

  - name: connectivity-default
    chart: ./connectivity
    namespace: default

  - name: connectivity-stg
    chart: ./connectivity
    namespace: stg

  - name: connectivity-prd
    chart: ./connectivity
    namespace: prd
