repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: twuni
    url: https://helm.twun.io

  - name: prefect
    url: https://prefecthq.github.io/prefect-helm

releases:
  - name: supa # the repo-provided index.yaml is wrong so we pullin
    chart: ./supabase-kubernetes/charts/supabase
    values:
      - supabase-values.yaml

  - name: mlflow
    chart: bitnami/mlflow
    values:
      - mlflow-values.yaml.gotmpl

  - name: prefect-worker
    chart: prefect/prefect-worker
    values:
      - prefect-worker-values.yaml

  - name: prefect-server
    chart: prefect/prefect-server
    values:
      - prefect-server-values.yaml

  - name: generic
    chart: ./generic
    values:
      - generic-values.yaml.gotmpl

  - name: vectorstore
    chart: ./vectorstore
