apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: vectorstore
  labels:
    app: vectorstore
    app.kubernetes.io/managed-by: Helm
  name: vectorstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vectorstore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vectorstore
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: pgvector
            - name: POSTGRES_PASSWORD
              value: pgvector
            - name: POSTGRES_USER
              value: pgvector
          image: ankane/pgvector
          name: vectorstore
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: vectorstore-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      restartPolicy: Always
      volumes:
        - name: vectorstore-data
          persistentVolumeClaim:
            claimName: vectorstore-data
        - name: init-sql
          configMap:
            name: pgvector-init-script
